### PR TITLE
Migrate to use Images from IAC ICR

### PR DESCRIPTION
**Pull request by daniel-butler-irl**
### Description

Changed where we pulled the images from and removed the image input variables as these should be managed by Renovate. Updated renovate configuration 

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [x] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

- If you currently use the image input variables these will need to be removed before consuming the new module version. 

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Comment by ocofaigh** [comment]
@daniel-butler-irl I think a minor version as we are removing variables. Did you manage to get the renovate config working as we want?

**Comment by ocofaigh** [comment]
Also, I notice pipeline failing with:
`Warning: Helm release "logdna-agent" was created but has a failed status. Use the `helm` command to investigate the error, correct it, then run Terraform again.`
`Warning: Helm release "sysdig-agent" was created but has a failed status. Use the `helm` command to investigate the error, correct it, then run Terraform again.`

You may need to locally deploy this to debug

**Comment by daniel-butler-irl** [comment]
closing in favor of https://github.com/terraform-ibm-modules/terraform-ibm-observability-agents/pull/275

**Pull request closed without merging**
