### PR TITLE
feat: refactor to make more flexible

### PR DESCRIPTION
**Pull request by ocofaigh**
### Description

- no longer require instance name and resource group. Instead just ask for instance region
- added initContainer to set up permissions for loopback feature to work
- chart cleanup
  - logdna cluster role was missing some roles
  - role binding is not namespace scoped, so removed it from yaml
  - exposed tolerations as input variable
  - added / updated annotations for checkov ignores
  - exposed namespace and release name as input variables
- readme cleanup
- removed unused file catalogValidationValues.json.template

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [x] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Review by vbontempi — APPROVED** [review]
changes look ok to me

**Review by vbontempi — APPROVED** [review]
ok

**Comment by ocofaigh** [comment]
@vbontempi I decided not to expose the `LOGDNA_DB_PATH` value as a terraform variable for now. Hit some issues when trying to test the initContainer, so for now I'm hard coding it in a local variable to `/var/lib/logdna`. 
Also I updated the cluster role rules again, based on further findings I found in the Openshift based chart.

**Comment by ocofaigh** [comment]
@vbontempi I managed to get the initContainer working, so have also included it in this PR

**Review by vbontempi — APPROVED** [review]
good for me

**Pull request merged**
