### PR TITLE
feat: add support for container filter

### PR DESCRIPTION
**Pull request by Aashiq-J**
### Description

Issue: https://github.ibm.com/GoldenEye/issues/issues/11264

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Comment by Aashiq-J** [comment]
```
                              - tolerationSeconds = null
                              - value             = null
                            },
                        ]
                    }
                )
              - version        = "0.1.0"
                # (2 unchanged attributes hidden)
            },
        ] -> (known after apply)
        name                       = "sysdig-agent"
      ~ values                     = [
            # (1 unchanged element hidden)
            <<-EOT
                "tolerations":
                - "effect": null
                  "key": null
                  "operator": "Exists"
                  "tolerationSeconds": null
                  "value": null
                - "effect": "NoSchedule"
                  "key": "node-role.kubernetes.io/master"
                  "operator": "Exists"
                  "tolerationSeconds": null
                  "value": null
            EOT,
          + <<-EOT
                "container_filter":
                - "name": "kube-system"
                  "parameter": "kubernetes.namespace.name"
                  "type": "exclude"
            EOT,
        ]
        # (25 unchanged attributes hidden)

        # (8 unchanged blocks hidden)
    }
```
Cloud monitoring agent will add this values which is causing the upgrade test to fail.

**Review by shemau — APPROVED** [review]
Looks good.

Can you add the release type and release notes to the description.

**Pull request merged**
