### PR TITLE
  Synchronize Sysdig agent ClusterRole

### PR DESCRIPTION
**Pull request by Ahmad-Slo**
### Description

With the current [Sysdig ClusterRole](https://github.com/terraform-ibm-modules/terraform-ibm-observability-agents/blob/main/chart/sysdig-agent/templates/clusterrole.yaml) in  the observability agent, Sysdig agents are not able to collect metrics for the enabled Sysdig monitoring integrations, e.g, cAdivsor, PVC, etc.
To enable that, the ClusterRole should include at least the following two resource:
```
  - nodes/metrics
  - nodes/proxy
```
This PR synchronizes Sysdig agent ClusterRole with the ClusterRole that is publicly available in Helm chart sysdig-deploy: https://github.com/sysdiglabs/charts/blob/main/charts/agent/templates/clusterrole.yaml

### Release required?

- [ ] No release
- [x ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Comment by Ahmad-Slo** [comment]
@ocofaigh I have not tried it. But it seems that there is an indentation issue. I fixed it and pushed the changes.

**Review by ocofaigh — APPROVED** [review]

**Pull request merged**
